server:
  port: 9001

#应用名称及验证账号
spring:
  application:
    name: api-passenger
  cloud:
    service-registry:
      auto-registration:
        enabled: true

eureka:
  client:
    #设置服务注册中心的URL, 集群的话，向一个IP注册就行, 会被封装成EurekaClientConfig，与Eureka服务器交互的
    service-url:
      defaultZone: http://root:root@eureka-7901:7901/eureka/
    #Client自身的配置信息
  instance:
    hostname: localhost
    instance-id: api-passenger